In [3]:
import pandas as pd

In [4]:
qa = pd.read_parquet('data/new_version_merged_df.parquet')

In [5]:
qa

,id,dataset,query,answer,context,context_length
0,nq_0,nq,who got the first nobel prize in physics,Wilhelm Conrad Röntgen,"`Dokument [ ""Nobel Prize in Physics"" ]:` recei...",1643
1,nq_1,nq,when is the next deadpool movie being released,"May 18, 2018","`Dokument [ ""Deadpool (video game)"" ]:` 2015 i...",1505
2,nq_2,nq,the south west wind blows across nigeria between,till September,"`Dokument [ ""Geography of Nigeria"" ]:` south a...",1442
3,nq_3,nq,what does hp mean in war and order,hit points or health points,"`Dokument [ ""Order of War"" ]:` Order of War Or...",1448
4,nq_4,nq,who wrote the first declaration of human rights,Cyrus,"`Dokument [ ""Drafting of the Universal Declara...",1670
...,...,...,...,...,...,...
6219,bioask_440,bioask,Jaki jest odsetek osób reagujących na leczenie...,Tetrabenazyna jest stosowana empirycznie w lec...,`Dokument [1]:` WPROWADZENIE: Zwapnienia mózgu...,1882
6220,bioask_715,bioask,Która kinaza jest hamowana przez Tripolinę A?,Tripolina A zmniejszała lokalizację pAurory A ...,`Dokument [1]:` Regulatory mitotyczne wykazują...,741
6221,bioask_1207,bioask,Jaka jest rola prognostyczna zmienionego profi...,Zmieniony profil tarczycy po operacji kardioch...,`Dokument [1]:` CEL: Pomimo poprawy postępowan...,4541
6222,bioask_1327,bioask,Czy istnieje różnica w szybkości fuzji i rozsz...,"Tak. W kilku badaniach oszacowano, że fuzja i ...",`Dokument [1]:` Domeny białkowe są zwartymi ew...,2840
6223,bioask_511,bioask,Czy mutacje BBS są związane z zespołową chorob...,W 3 rodzinach z zespołem Bardeta-Biedla (BBS) ...,`Dokument [1]:` Choroba Hirschsprunga (HSCR) j...,494

In [6]:
cnndm = pd.read_parquet('data/cnndm.parquet')

In [7]:
cnndm

,id,dataset,question,context,answer,context_length
0,cnndm_0,cnndm,Generate a summary comprising of 1 sentence fo...,"Marseille, France (CNN)The French prosecutor l...","Marseille prosecutor says ""so far no videos we...",1572
1,cnndm_1,cnndm,Generate a summary comprising of 1 sentence fo...,He's a blue chip college basketball recruit. S...,College-bound basketball star asks girl with D...,719
2,cnndm_2,cnndm,Generate a summary comprising of 1 sentence fo...,The United States and its negotiating partners...,Richard Klass: Iran framework agreement on nuk...,1105
3,cnndm_3,cnndm,Generate a summary comprising of 1 sentence fo...,"Police in the Indian city of Malegaon, in the ...",Authorities in the Indian city of Malegaon hav...,599
4,cnndm_4,cnndm,Generate a summary comprising of 1 sentence fo...,The terrorist group Al-Shabaab has claimed an ...,Terrorist group Al-Shabaab has attacked a Keny...,1115
...,...,...,...,...,...,...
995,cnndm_995,cnndm,Generate a summary comprising of 1 sentence fo...,While Google and Apple are developing self dri...,Modular Robotic Vehicle developed at NASA's Jo...,1123
996,cnndm_996,cnndm,Generate a summary comprising of 1 sentence fo...,Staff attorneys at the U.S. Justice Department...,Attorneys at the U.S. Justice Department may r...,754
997,cnndm_997,cnndm,Generate a summary comprising of 1 sentence fo...,It was the most heartbreaking tragedy of the f...,Zane Gbangbola died at home in the middle of t...,1643
998,cnndm_998,cnndm,Generate a summary comprising of 1 sentence fo...,Help for Heroes has launched a fundraising dri...,Great-grandfather Robert Clark has lived in th...,1401
999,cnndm_999,cnndm,Generate a summary comprising of 1 sentence fo...,The Tulsa County Sheriff's Office falsified th...,Tulsa County Sheriff's Office falsified Robert...,1254

In [8]:
xsum = pd.read_parquet('data/xsum_df.parquet')

In [9]:
xsum

,id,question,context,answer,dataset,context_length
0,xsum_38264402,Generate a summary comprising of 1 sentence fo...,"`Dokument [1]:` Prison Link Cymru had 1,099 re...","There is a ""chronic"" need for more housing for...",xsum,912
1,xsum_38521798,Generate a summary comprising of 1 sentence fo...,"`Dokument [1]:` Iwan Wyn Lewis of Penygroes, G...",North Wales Police has been criticised at an i...,xsum,441
2,xsum_27119429,Generate a summary comprising of 1 sentence fo...,`Dokument [1]:` The fine follows the convictio...,Royal Bank of Scotland (RBS) has been fined HK...,xsum,469
3,xsum_18298438,Generate a summary comprising of 1 sentence fo...,`Dokument [1]:` It is believed to be the first...,A suspected terrorist has been charged with br...,xsum,536
4,xsum_40191593,Generate a summary comprising of 1 sentence fo...,`Dokument [1]:` Dan Coats also told a Senate p...,The US director of national intelligence has s...,xsum,867
...,...,...,...,...,...,...
995,xsum_38208884,Generate a summary comprising of 1 sentence fo...,`Dokument [1]:` The accusations were made by R...,Charlton Athletic have begun an investigation ...,xsum,493
996,xsum_39380075,Generate a summary comprising of 1 sentence fo...,`Dokument [1]:` The boards are forecast to ove...,Four health boards which are due to see their ...,xsum,1000
997,xsum_39192785,Generate a summary comprising of 1 sentence fo...,`Dokument [1]:` Nintendo said such pixels were...,"Thousands of owners of Nintendo's new console,...",xsum,636
998,xsum_39207593,Generate a summary comprising of 1 sentence fo...,`Dokument [1]:` Philip Hammond says the extra ...,The chancellor has announced a £2bn rescue pac...,xsum,1007
999,xsum_35860140,Generate a summary comprising of 1 sentence fo...,"`Dokument [1]:` The 56-year-old man, from Esse...",A pilot has died after his microlight hit an e...,xsum,296

In [10]:
full_ds = pd.read_parquet('data/full_hallu_ds.parquet')

In [11]:
full_ds

,id,dataset,query,answer,context,context_length,question
0,nq_0,nq,who got the first nobel prize in physics,Wilhelm Conrad Röntgen,"`Dokument [ ""Nobel Prize in Physics"" ]:` recei...",1643,None
1,nq_1,nq,when is the next deadpool movie being released,"May 18, 2018","`Dokument [ ""Deadpool (video game)"" ]:` 2015 i...",1505,None
2,nq_2,nq,the south west wind blows across nigeria between,till September,"`Dokument [ ""Geography of Nigeria"" ]:` south a...",1442,None
3,nq_3,nq,what does hp mean in war and order,hit points or health points,"`Dokument [ ""Order of War"" ]:` Order of War Or...",1448,None
4,nq_4,nq,who wrote the first declaration of human rights,Cyrus,"`Dokument [ ""Drafting of the Universal Declara...",1670,None
...,...,...,...,...,...,...,...
995,xsum_38208884,xsum,None,Charlton Athletic have begun an investigation ...,`Dokument [1]:` The accusations were made by R...,493,Generate a summary comprising of 1 sentence fo...
996,xsum_39380075,xsum,None,Four health boards which are due to see their ...,`Dokument [1]:` The boards are forecast to ove...,1000,Generate a summary comprising of 1 sentence fo...
997,xsum_39192785,xsum,None,"Thousands of owners of Nintendo's new console,...",`Dokument [1]:` Nintendo said such pixels were...,636,Generate a summary comprising of 1 sentence fo...
998,xsum_39207593,xsum,None,The chancellor has announced a £2bn rescue pac...,`Dokument [1]:` Philip Hammond says the extra ...,1007,Generate a summary comprising of 1 sentence fo...
999,xsum_35860140,xsum,None,A pilot has died after his microlight hit an e...,"`Dokument [1]:` The 56-year-old man, from Esse...",296,Generate a summary comprising of 1 sentence fo...

In [ ]:
import torch

In [ ]:
test = torch.load('outputs/step01_cnndm_test.pt')

In [3]:
len(test)

998